# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-07 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='flag',
            field=models.BooleanField(default=0, verbose_name='是否出货'),
        ),
    ]
