# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-07 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20210607_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commodity',
            options={'verbose_name_plural': '货物表'},
        ),
        migrations.AlterModelOptions(
            name='factory',
            options={'verbose_name_plural': '工厂表'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': '流动信息表'},
        ),
        migrations.RenameField(
            model_name='f2c',
            old_name='name',
            new_name='commodity',
        ),
    ]
