# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-07 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210607_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='factory',
        ),
    ]
