# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-06-07 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_commodity_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='factory',
            field=models.ManyToManyField(through='app01.F2C', to='app01.Factory'),
        ),
    ]
